### ISSUE TITLE
Unable to share screen

### ISSUE THREAD

**Issue by tim-andes** [vasanthv/ahey#10]
Connected via windows 10. Using Pixel 4a as webcam/mic with droidcam app. Audio/video seems to work with droidcam app, but when I try to share screen, I get popup "Unable to share screen", but at the bottom it does say "http://localhost:3000/ is sharing your screen".

Unsure if successfully sharing screen or not. Happy to test it with someone
![unabletosharescreen](https://user-images.githubusercontent.com/64085493/92952539-1e2a8f00-f42e-11ea-8e98-059294ebf6f9.jpg)

**Comment by ricardoGonzf** [comment]
Same thing is happening to me, also when i try to flip the cam

**Comment by oscarcornejo** [comment]
share screen not working!

**Comment by vasanthv** [comment]
Sorry for the delayed response. Its fixed now.
