### ISSUE TITLE
Infinite loop if you share the desktop on which the app is in 

### ISSUE THREAD

**Issue by toast38coza** [vasanthv/ahey#15]
System information: iOS, Chrome

Steps to replicate:
* Click share screen
* With the browser in the foreground, choose the desktop with talk in the foreground.
* Result: Hall of mirrors (see screenshot)

<img width="1467" alt="Screenshot 2021-04-27 at 00 49 31" src="https://user-images.githubusercontent.com/517966/116160719-d887b180-a6f2-11eb-9aff-7ff5e7cd6425.png">

**Comment by vasanthv** [comment]
@toast38coza this is the expected behaviour if we are screen sharing the call video. It should look fine if you switch to a different window or tab.
