### ISSUE TITLE
Alter Stream Quality

### ISSUE THREAD

**Issue by wayneconnolly** [vasanthv/ahey#21]
Hello, first thank you! This is fantastic. We are using it and I will do a pull request for a new docker-compose that uses jwilder. So thanks!

Question: Currently the quality of the streams (video/audio) can't be changed or even seen via some status. Is it possible in webRTC to change the video and/or audio quality? It may not even be possible... just asking...

**Comment by vasanthv** [comment]
@wayneconnolly yes I guess it should be possible with `MediaStreamTrack.applyConstraints`. But that is not in my pipeline for now.
