### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by mohsinalimat** [vasanthv/ahey#23]
Hello,

I like this repository.
Please add end meeting call button feature.

**Comment by vasanthv** [comment]
@mohsinalimat Any reason for needing this button? You can always close the window to end the meeting.

**Comment by mohsinalimat** [comment]
Because If a user wants to end the call from his/her side. and Admin user can end call from admin side.

**Comment by vasanthv** [comment]
Currently, Talk doesn't have the concept of admin and it will not have in the future as well. The motto is "No signup. No downloads". Bringing in the concept of admin without user signup won't work. 
Coming to "End meeting", you will never be able to end the meeting for all in Talk, you can only leave the meeting (by closing the window/tab).

**Comment by mohsinalimat** [comment]
Great. 👍
