### ISSUE TITLE
Localhost access only

### ISSUE THREAD

**Issue by Erispoe1** [vasanthv/ahey#28]
hello,

Talk is great !! I like it and i install it on a VM on my network. But I have a question?
I have access with "Locahost" with a ssh Tunnel .
But how can I use it with en IP  of my local network ?
I tried with Haproxy with Frontend Ip of local network and Backend "localhost" , I tried with an IP of my local network....But nothing, I just have static page of talk nevertheless I can't use it (camera, microphone...)

Thanks

**Comment by asher-lab** [comment]
Looks like the repo can't be built

**Comment by vasanthv** [comment]
The browsers won't allow video & audio access to IP addresses. Try setting up a domain for your local IP and check it out. Let me know your results. Also, if you see any console errors, please do share them as well.

**Comment by Erispoe1** [comment]
hello,

With HAPROXY,  I create an HTTPS reverse-proxy and now TALK  is active with IP of local network .
Nevertheless, I can't see and listen the another client. I just see Myself in talk :):) 
In Progress...:):)

**Comment by MuzafferDede** [comment]
the video and audio streaming works if you run locally. not sure what cause this. it might be related to the stun and turn servers. free ones are not working maybe.

**Comment by vasanthv** [comment]
@MuzafferDede were you able to use the service using https://usetalk.io ? or even that can be used only in the local network?

**Comment by MuzafferDede** [comment]
I actually pulled this repo and deployed to heroku, it works fine. I am also working on a project and i face this issue that if i connect between different ip address, can't transfer video and audio, but there is no error at all. all i seen that people says it's because stun and turn servers... i use same as yours, still doesn't work

**Comment by jasteyn07** [comment]
> @MuzafferDede were you able to use the service using https://usetalk.io ? or even that can be used only in the local network?

Hi there, I have the same issue and I have this issue on https://usetalk.io/ also. If i log on locally from my network with other devices I can see all screens, but If I connect via GSM (mobile not on my local Wifi network) the participant for this one has a blank screen, no chat messages go through and no audio video, only a blank block. From the Railway.app I can see that participants are connecting and IP's are there, but no communication. I have changed the Stun and Turn servers to my own. Both the fork version with my own stun/turn server and the master code from your repo has the same issue and as mentioned also on your hosted platform. Can you perhaps assist? Thank you for the good work BTW!!

**Comment by vasanthv** [comment]
@MuzafferDede Can you try to change the ICE_SERVERS to use only Turn server and check if its working across networks?

Change the following line https://github.com/vasanthv/talk/blob/master/www/script.js#L2-L19 to 

```javascript
const ICE_SERVERS = [{ urls: "turn:numb.viagenie.ca", username: "imvasanthv@gmail.com", credential: "d0ntuseme" }];
```

The reason I couldn’t test it, I couldn't find a Symmetric NAT implementation to test it. As symmetric Nat needs TURN servers and STUN servers won't work for it.

**Comment by miroslavpejic85** [comment]
I'm agree with @vasanthv,

If that doesn't work with `viagenie.ca`, try also this one:

```js
const ICE_SERVERS = [{ urls: "turn:openrelay.metered.ca:443", username: "openrelayproject", credential: "openrelayproject"}];
```
</br>
Regards.

**Comment by vasanthv** [comment]
@Erispoe1  Closing this for now. Reopen it if this is not fixed for you yet.
