### ISSUE TITLE
Unable to communicate between (ANY) networks?

### ISSUE THREAD

**Issue by AleDenshi** [vasanthv/ahey#29]
Hello. I recently setup talk on a personal server, running it behind a reverse-proxy (NGINX) at my own [domain name.](https://talk.denshi.live)

I have attempted to connect to the instance from the local network, and from the internet, but while the other user does show up on the instance, no audio or video communication happens.

The server I'm hosting this on is under no NAT or firewall, so no ports are being blocked.

Is there something I've missed?

**Comment by vasanthv** [comment]
Do you see any errors in the console?

**Comment by miroslavpejic85** [comment]
Hello @AleDenshi, 
Check out this doc: https://github.com/vasanthv/talk/blob/master/docs/self-hosting.md
Try the last version, and make sure to expose Talk on `HTTPS`.
