### ISSUE TITLE
Can't allow camera and microphone

### ISSUE THREAD

**Issue by daphniz** [vasanthv/ahey#3]
Windows/Chrome doesn't offer any way to allow camera and microphone.

**Comment by eti0** [comment]
same here on macos (10.15.6) with google chrome (83.0.4103.61).
even after enabling microphone and camera access manually, talk still assumes it doesn't have the proper authorizations.

![image](https://user-images.githubusercontent.com/14180792/92306305-5a717180-ef8e-11ea-9a00-0bc4bf4d1b25.png)

**Comment by JustDevNull** [comment]
It seems that it only asks for both if you have a webcam, this also means that you're forced to have a webcam to be able to use it.

**Comment by eti0** [comment]
i see. i do not have a webcam so that makes sense.

**Comment by maxdoes** [comment]
I am having this issue in both Chrome and Safari on both MacOS, iOS, and Android.

**Comment by asher-lab** [comment]
In chrome version 46 and up, the browser will not allow the use of camera and microphone unless you are on https connection. 
https://stackoverflow.com/questions/52759992/how-to-access-camera-and-microphone-in-chrome-without-https
