### ISSUE TITLE
[Feature Request] Remove usetalk.io Specific Links in a Build Phase

### ISSUE THREAD

**Issue by tomershvueli** [vasanthv/ahey#30]
Hello! 

I just came across this project and am in awe! You managed to create such a powerful tool with such simple code, it's really quite something :) 

I would like to package this and self host it on my own server, but noticed a few instances in the www/index.html that reference usetalk.io directly, including an analytics script, and hard-coded STUN/TURN servers. Would you consider pulling these things conditionally based on some environment variables or a build script potentially? Or would you consider merging in a PR that would implement this? 

Thanks for your hard work!

**Comment by vasanthv** [comment]
Should be done in https://github.com/vasanthv/talk/pull/42
