### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by PranavArya37** [vasanthv/ahey#32]
There is no leave button to leave the Call

**Comment by PranavArya37** [comment]
Hyperlinks are not clickable in the chatbox and also time is not updating in realtime

**Comment by vasanthv** [comment]
> There is no leave button to leave the Call

Talk will not have leave button, which is explained in this ticket. https://github.com/vasanthv/talk/issues/23

**Comment by vasanthv** [comment]
> Hyperlinks are not clickable in the chatbox and also time is not updating in realtime

Thanks for this suggestion. This is now added in commits dd9a6fb2a76a5a78bbe1e571ed702b2e8cfe3691 & 8111d58b6c69ebd3b020a0f76d73bf4f79be5f11
