### ISSUE TITLE
maximum connections

### ISSUE THREAD

**Issue by chrigui** [vasanthv/ahey#35]
Let's assume i want to run a live webinar with presenter Cam and Mic ON only. How many users can connect to view and listen on a 2GB VPS ?
is there a formula to calculate this?
have  you done any tests to calculate server requirements?

**Comment by vasanthv** [comment]
All the connections in the Talk are peer-to-peer. So if 8 users are in a call it means each person is connected to 7 different streams for video/audio communication. This makes it unsuitable for webinar kind of one-to-many video communication. We haven't done any tests for the number of users that can join the call as it depends on the user's bandwidth and not servers.
