### ISSUE TITLE
Opening one tab does not closes others which creates an overlap

### ISSUE THREAD

**Issue by shreyshreyansh** [vasanthv/ahey#36]
![Screenshot 2021-08-16 093756](https://user-images.githubusercontent.com/53744971/129510319-f4730c17-944a-4013-824a-1925fc3efe88.png)

**Comment by miroslavpejic85** [comment]
@shreyshreyansh On `script.js` just add this 4 lines.

![ScriptJS](https://user-images.githubusercontent.com/70838434/183727432-7c1a1aa3-de17-41cd-a97a-a4df1a180921.png)

**Comment by miroslavpejic85** [comment]
Hi @shreyshreyansh, 
should be fixed with this merge: https://github.com/vasanthv/talk/pull/42
