### ISSUE TITLE
Leaked username/password in frontend?

### ISSUE THREAD

**Issue by jgmullor** [vasanthv/ahey#4]
Hi @vasanthv! On line 41/42 on the frontend script, seems like you published an username/password? Or is it just an example?
https://github.com/vasanthv/talk/blob/da53c07f688c9b21c7e42f383b8580329a09901e/www/script.js#L41

Nice project!! =)

Thank you.

**Comment by vasanthv** [comment]
@jgmullor Yes that was intentional, that's how you connect to TURN servers.

**Comment by Fastidious** [comment]
If I were to run my own STUN server, what do I need to change the lines to? I would like to only leave my server in it. Thanks!
