### ISSUE TITLE
'Leave' or 'Hangup'-button missing?

### ISSUE THREAD

**Issue by pragmatech** [vasanthv/ahey#43]
Am I somehow overlooking the typical 'End Call' button? 
If not, is there a back story to its absence?
Thanks for sharing this nice webrtc implementation! It seems to run on my little GCP server just fine. As another aside to this question, I only 'discovered' this through miroslavpejic85 having forked it. He has been extremely giving and helpful in this area as well.

**Comment by pragmatech** [comment]
Apologies if I failed to appreciate vasanthv's minimalism – in so rashly evaluating the exit-button's absence. From another perspective (say, using Talk in an iframe), keeping UI options open seems preferrable, to an exit button that essentially opens a new randomised-room id instance. Thanks!

**Comment by vasanthv** [comment]
@miroslavpejic85 addressed this in https://github.com/vasanthv/talk/pull/42
