### ISSUE TITLE
Self hosting but cannot work and does not show a link

### ISSUE THREAD

**Issue by luym11** [vasanthv/ahey#45]
I can access this page in my local network and also from outside (my server is hooked at a public IP address).
However, in both case, I cannot see video and does not see a link as how it is like on the maintainer's website. 

I browsed through the issues and did not find a similar one. 
Could you please shed some light? Thanks! 

![Screenshot 2022-10-26 at 23 36 51](https://user-images.githubusercontent.com/6823040/198143248-e6a3ffd1-15b7-49a9-9d59-723d401b166d.png)

**Comment by miroslavpejic85** [comment]
Hello @luym11,

If you trying to self host it, You have to reach your server in `HTTPS` not in `HTTP` (You can do it in different ways). If you have a domain/subdomain name Set a DNS A record for that domain that point to Your Server public IPv4 and expose it in HTTPS. If you are not familiar with using [nginx](https://www.nginx.com/), [certbot](https://certbot.eff.org/) ..., you can try with `ngrok` by following this doc: https://github.com/vasanthv/talk/blob/master/docs/ngrok.md

**Comment by luym11** [comment]
Hi @miroslavpejic85,

Thanks for your timely answer! It seems that this is the case. I will try as you suggested.

**Comment by luym11** [comment]
@miroslavpejic85  
One suggestion: maybe it worth mentioning that `HTTPS` is required for self-hosting in the main readme page.

**Comment by miroslavpejic85** [comment]
> Hi @miroslavpejic85,
> 
> Thanks for your timely answer! It seems that this is the case. I will try as you suggested.

You are welcome.

**Comment by miroslavpejic85** [comment]
> @miroslavpejic85
> One suggestion: maybe it worth mentioning that `HTTPS` is required for self-hosting in the main readme page.

All done in this commit: https://github.com/vasanthv/talk/commit/6738a45f1fb07ef0a5d482f2dfce65e9d4c69895

You can check out now how to self host Talk here: https://github.com/vasanthv/talk/blob/master/docs/self-hosting.md

Thank you for the suggestion.
