### ISSUE TITLE
IPhone Full Screen Issue

### ISSUE THREAD

**Issue by a-gholami** [vasanthv/ahey#46]
Hi
i am so grateful for this amazing web app
i found an issue on iphone Safari browser,
the fullscreen button not works
you can try and test it online by using [browserstack.com](https://www.browserstack.com/)
Thank you

**Comment by miroslavpejic85** [comment]
After conducting some research, it appears that [Safari](https://caniuse.com/fullscreen) and other browsers on an `iPhone` do not support the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). As a result, it seems necessary to either find an alternative solution or hide the fullscreen button when accessing the website on an iPhone.
