### ISSUE TITLE
App only works between devices on the same local network

### ISSUE THREAD

**Issue by JustDevNull** [vasanthv/ahey#6]
After testing both [the provided talk server](https://talk.vasanthv.com/) and one I had hosted while testing the docker-compose solution I found out that it doesn't show the other person webcam/voice if we are in separate networks.

After testing with two laptops from the same local network it seems to work.

Tested with Brave, Edge and Firefox. Also with a phone.

Maybe an issue with STUN/TUN?

**Comment by ShonFrazier** [comment]
I saw it work across the wider internet, but only intermittently. My companion would appear, we could share audio for 15-30sec, and she'd just drop off. I'm running the server in my local network. The server console output would show the disconnect from her end.

**Comment by vasanthv** [comment]
@JustDevNull Where you using the demo app `talk.vasanthv.com` or your own local instance?

**Comment by JustDevNull** [comment]
Tried both, and my instance was deployed in a VPS.

**Comment by lmangani** [comment]
You probably need a TURN server

**Comment by JustDevNull** [comment]
I tried adding turn servers to the APP settings, but got the same result.

**Comment by chrismatthieu** [comment]
FYI, I am able to talk to people on local net and outside of local net just fine.

**Comment by vasanthv** [comment]
Never faced this, not even once. Closing it for now, let's see if it still happens.
