### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by deilton16** [vasanthv/ahey#64]
It's cool

**Comment by vasanthv** [comment]
Hi, I have create a new branch for the local setup. https://github.com/vasanthv/talk/tree/local-setup

Run `npm start`. That should run both signalling server & the UI. With this commit "https://github.com/vasanthv/talk/commit/d9fa48341bc1db9b4149c3cac686563071b896f8". You can hopefully understand what needs to be changed for your deployment.

**Comment by deilton16** [comment]
you are awesome !!! Thanks !!!
