### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by agevlakh** [vasanthv/ahey#67]
Hello!
I made all like in description.
But then I come to http://ip-my-server:3000 I get error in my browser
Cannot GET /
Please help
FreeBSS 14.1 nodejs 20

**Comment by FruitJelliesGD** [comment]
me too
```
npm -version
10.8.2
```
```
node -v
v20.18.0
```

**Comment by agevlakh** [comment]
> me too
> 
> ```
> npm -version
> 10.8.2
> ```
> 
> ```
> node -v
> v20.18.0
> ```

Just use this fork. https://github.com/miroslavpejic85/talk

**Comment by FruitJelliesGD** [comment]
> Just use this fork. https://github.com/miroslavpejic85/talk 

Only my server can connect to audio and video from localhost. Devices on the local network or the public network can only reach the username input step. After accessing the room page, they don’t actually enter the room. Modifying the `const APP_URL` in WebRTC to the server's IP address doesn’t solve the issue either.

**Comment by agevlakh** [comment]
You also need setup your turn server (coturn) for this and change address in app.js @FruitJelliesGD

**Comment by agevlakh** [comment]
Also you need https certificate, letsencrypt for example. Simple use nginx proxy @FruitJelliesGD

**Comment by FruitJelliesGD** [comment]
Thank you for your patient guidance. I am working hard to figure it out and trying to get [Talk](https://github.com/vasanthv/talk) running within the private network of this tool group [vnt-dev/VntApp](https://github.com/vnt-dev/VntApp).Because my network environment here is really terrible.

**Comment by agevlakh** [comment]
> Thank you for your patient guidance. I am working hard to figure it out and trying to get [Talk](https://github.com/vasanthv/talk) running within the private network of this tool group [vnt-dev/VntApp](https://github.com/vnt-dev/VntApp).Because my network environment here is really terrible.

You are welcome. Open for your questions

**Comment by vasanthv** [comment]
This is resolved now.
