### ISSUE TITLE
Multiple cameras

### ISSUE THREAD

**Issue by darkpixel** [vasanthv/ahey#7]
I have multiple cameras.  The app doesn't have a "camera chooser" and it appears to default to the first video device on the system.  The first video device on my system isn't really a video device and the app doesn't appear to like it.

In 'talk':
![Screenshot from 2020-09-05 20-03-32](https://user-images.githubusercontent.com/158380/92317208-48ee9080-efb3-11ea-9469-da6587e2bcde.png)

Showing that it works in Google Meet:
![Screenshot from 2020-09-05 20-04-16](https://user-images.githubusercontent.com/158380/92317214-5572e900-efb3-11ea-8899-4e39ba74fdc4.png)

**Comment by ShonFrazier** [comment]
This is currently a known bug with Chrome. Have you tried another browser?

**Comment by darkpixel** [comment]
Not yet.  If it's already known, no worries.  I just wanted to let you know.

**Comment by darkpixel** [comment]
Just tested in Firefox and it works.

**Comment by vasanthv** [comment]
Chrome will only allow you to choose the camera after allowing access. 
<img width="1440" alt="Screenshot 2020-09-10 at 12 36 48" src="https://user-images.githubusercontent.com/780907/92692906-801dc280-f362-11ea-873d-e516a7bf58f7.png">
