### ISSUE TITLE
Offer setLocalDescription failed!

### ISSUE THREAD

**Issue by JohnnyZhang0628** [vasanthv/ahey#8]
when i try to open 4 tabs in edge,i got a exception "Offer setLocalDescription failed!".
my screenshot：
![image](https://user-images.githubusercontent.com/28375774/92375099-37cc8d80-f133-11ea-93f3-46f388f0392b.png)

**Comment by chrismatthieu** [comment]
I get the same error in Chrome and Safari when trying to connect more than 3 sessions. I'm using incognito mode to avoid session errors but experience the same error.

**Comment by chrismatthieu** [comment]
I tested it today on multiple machines thinking maybe the problem was related to signaling on the same machine. Same issue.

**Comment by vasanthv** [comment]
Please share any errors from the console.
