### ISSUE TITLE
Allow access without webcam

### ISSUE THREAD

**Issue by tschuehly** [vasanthv/ahey#9]
I really would like to use this project, but the need for a webcam for every user is not optimal, some of my mates don't have a webcam so it would be great if you could use the website without a camera.

**Comment by kristijanPetr** [comment]
@tschuehly you can use something like this - to have error fallback function if it fails on Camera to try with video set to `false`
```
navigator.mediaDevices
    .getUserMedia({ audio: USE_AUDIO, video: USE_VIDEO })
    .then((stream) => {
      return onSuccessGetMedia(stream, callback);
    })
    .catch(() => {
      navigator.mediaDevices
        .getUserMedia({ audio: USE_AUDIO, video: false })
        .then((stream) => {
          return onSuccessGetMedia(stream, callback);
        })
        .catch((err) => {
          alert('This app will not work without camera/microphone access.');
          if (errorback) errorback();
        });

      /* user denied access to a/v */
    });
```

**Comment by 3291823** [comment]
This did not work,, perhaps it would be better to request permissions after clicking on the video/microphone buttons...

**Comment by Owned-by-Luce** [comment]
how to display  name on video?

**Comment by seriseyes** [comment]
how to display name on video?
Example
![temp](https://user-images.githubusercontent.com/64944379/122366120-dbce4980-cf8d-11eb-8532-0d39cbfaeac8.png)
